export const SEED_EXERCISES = [

  // ── CHEST — MID ───────────────────────────────────────────────────────────
  { id: 'bench_barbell', name: 'Bench Press (Barbell)', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'bench_dumbbell', name: 'Bench Press (Dumbbell)', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'horizontal', bilateral: true },
  { id: 'smith_bench', name: 'Bench Press (Smith Machine)', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Smith Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'chest_press_machine', name: 'Chest Press (Machine)', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'fly_cable', name: 'Fly (Cable)', primary_muscle: 'Mid Chest', secondary_muscle: null, movement_pattern: 'Fly', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: true },
  { id: 'fly_dumbbell', name: 'Fly (Dumbbell)', primary_muscle: 'Mid Chest', secondary_muscle: null, movement_pattern: 'Fly', equipment_type: 'Dumbbell', force_vector: 'horizontal', bilateral: true },
  { id: 'pec_deck', name: 'Pec Deck', primary_muscle: 'Mid Chest', secondary_muscle: null, movement_pattern: 'Fly', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'pushup', name: 'Push-Up', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'pushup_wide', name: 'Wide Push-Up', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'svend_press', name: 'Svend Press', primary_muscle: 'Mid Chest', secondary_muscle: null, movement_pattern: 'Fly', equipment_type: 'Plate', force_vector: 'horizontal', bilateral: true },

  // ── CHEST — UPPER ─────────────────────────────────────────────────────────
  { id: 'bench_incline_barbell', name: 'Incline Press (Barbell)', primary_muscle: 'Upper Chest', secondary_muscle: 'Shoulders', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'diagonal', bilateral: true },
  { id: 'bench_incline_dumbbell', name: 'Incline Press (Dumbbell)', primary_muscle: 'Upper Chest', secondary_muscle: 'Shoulders', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: true },
  { id: 'bench_incline_machine', name: 'Incline Press (Machine)', primary_muscle: 'Upper Chest', secondary_muscle: 'Shoulders', movement_pattern: 'Push', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'bench_incline_smith', name: 'Incline Press (Smith Machine)', primary_muscle: 'Upper Chest', secondary_muscle: 'Shoulders', movement_pattern: 'Push', equipment_type: 'Smith Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'cable_fly_high', name: 'High Fly (Cable)', primary_muscle: 'Upper Chest', secondary_muscle: null, movement_pattern: 'Fly', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: true },
  { id: 'fly_incline_dumbbell', name: 'Incline Fly (Dumbbell)', primary_muscle: 'Upper Chest', secondary_muscle: null, movement_pattern: 'Fly', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: true },
  { id: 'fly_incline_cable', name: 'Incline Fly (Cable)', primary_muscle: 'Upper Chest', secondary_muscle: null, movement_pattern: 'Fly', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: true },
  { id: 'landmine_press_chest', name: 'Landmine Press', primary_muscle: 'Upper Chest', secondary_muscle: 'Shoulders', movement_pattern: 'Push', equipment_type: 'Landmine', force_vector: 'diagonal', bilateral: false },
  { id: 'pushup_incline', name: 'Incline Push-Up', primary_muscle: 'Upper Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: true },

  // ── CHEST — LOWER ─────────────────────────────────────────────────────────
  { id: 'bench_decline_barbell', name: 'Decline Press (Barbell)', primary_muscle: 'Lower Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'diagonal', bilateral: true },
  { id: 'bench_decline_dumbbell', name: 'Decline Press (Dumbbell)', primary_muscle: 'Lower Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: true },
  { id: 'bench_decline_smith', name: 'Decline Press (Smith Machine)', primary_muscle: 'Lower Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Smith Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'cable_fly_low', name: 'Low Fly (Cable)', primary_muscle: 'Lower Chest', secondary_muscle: null, movement_pattern: 'Fly', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: true },
  { id: 'dip_chest', name: 'Chest Dip', primary_muscle: 'Lower Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: true },
  { id: 'pushup_decline', name: 'Decline Push-Up', primary_muscle: 'Lower Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: true },
  { id: 'pushup_diamond', name: 'Diamond Push-Up', primary_muscle: 'Lower Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },

  // ── BACK — LATS ───────────────────────────────────────────────────────────
  { id: 'pullup', name: 'Pull-Up', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'pullup_wide', name: 'Wide-Grip Pull-Up', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'pullup_neutral', name: 'Neutral-Grip Pull-Up', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'chinup', name: 'Chin-Up', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'inverted_row', name: 'Inverted Row', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'pulldown_lat', name: 'Lat Pulldown (Cable)', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'pulldown_lat_wide', name: 'Wide-Grip Lat Pulldown (Cable)', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'pulldown_lat_close', name: 'Close-Grip Lat Pulldown (Cable)', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'pulldown_lat_single', name: 'Single-Arm Lat Pulldown (Cable)', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: false },
  { id: 'row_dumbbell', name: 'Row (Dumbbell)', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'horizontal', bilateral: false },
  { id: 'row_dumbbell_chest_supported', name: 'Chest-Supported Row (Dumbbell)', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'horizontal', bilateral: true },
  { id: 'pullover_machine', name: 'Pullover (Machine)', primary_muscle: 'Lats', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'pullover_dumbbell', name: 'Pullover (Dumbbell)', primary_muscle: 'Lats', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: true },
  { id: 'pullover_cable', name: 'Pullover (Cable)', primary_muscle: 'Lats', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: true },
  { id: 'straight_arm_pulldown', name: 'Straight-Arm Pulldown (Cable)', primary_muscle: 'Lats', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },

  // ── BACK — UPPER ──────────────────────────────────────────────────────────
  { id: 'row_barbell', name: 'Row (Barbell)', primary_muscle: 'Upper Back', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'row_underhand_barbell', name: 'Underhand Row (Barbell)', primary_muscle: 'Upper Back', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'row_pendlay', name: 'Pendlay Row (Barbell)', primary_muscle: 'Upper Back', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'row_tbar', name: 'T-Bar Row', primary_muscle: 'Upper Back', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'row_meadows', name: 'Meadows Row (Barbell)', primary_muscle: 'Upper Back', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: false },
  { id: 'row_cable', name: 'Row (Cable)', primary_muscle: 'Upper Back', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: true },
  { id: 'row_seated_cable', name: 'Seated Row (Cable)', primary_muscle: 'Upper Back', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: true },
  { id: 'row_cable_single', name: 'Single-Arm Row (Cable)', primary_muscle: 'Upper Back', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: false },
  { id: 'row_machine', name: 'Row (Machine)', primary_muscle: 'Upper Back', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'row_chest_supported_machine', name: 'Chest-Supported Row (Machine)', primary_muscle: 'Upper Back', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'smith_row', name: 'Row (Smith Machine)', primary_muscle: 'Upper Back', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Smith Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'facepull', name: 'Face Pull', primary_muscle: 'Rear Delts', secondary_muscle: 'Upper Back', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: true },

  // ── BACK — LOWER ──────────────────────────────────────────────────────────
  { id: 'deadlift', name: 'Deadlift (Barbell)', primary_muscle: 'Lower Back', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'deadlift_sumo', name: 'Sumo Deadlift (Barbell)', primary_muscle: 'Lower Back', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'deadlift_trap_bar', name: 'Deadlift (Trap Bar)', primary_muscle: 'Lower Back', secondary_muscle: 'Quads', movement_pattern: 'Hinge', equipment_type: 'Trap Bar', force_vector: 'vertical', bilateral: true },
  { id: 'deadlift_stiff_leg', name: 'Stiff-Leg Deadlift (Barbell)', primary_muscle: 'Lower Back', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'rack_pull', name: 'Rack Pull (Barbell)', primary_muscle: 'Lower Back', secondary_muscle: 'Traps', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'hyperextension', name: 'Back Extension', primary_muscle: 'Lower Back', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'hyperextension_machine', name: 'Back Extension (Machine)', primary_muscle: 'Lower Back', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'good_morning', name: 'Good Morning (Barbell)', primary_muscle: 'Lower Back', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'cable_pull_through', name: 'Cable Pull-Through', primary_muscle: 'Lower Back', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: true },

  // ── SHOULDERS — COMPOUND ──────────────────────────────────────────────────
  { id: 'press_ohp', name: 'Overhead Press (Barbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'press_dumbbell_shoulder', name: 'Shoulder Press (Dumbbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'shoulder_press_machine', name: 'Shoulder Press (Machine)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'smith_ohp', name: 'Overhead Press (Smith Machine)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Smith Machine', force_vector: 'vertical', bilateral: true },
  { id: 'arnold_press', name: 'Arnold Press (Dumbbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'push_press', name: 'Push Press (Barbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'landmine_press_shoulder', name: 'Landmine Shoulder Press', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Landmine', force_vector: 'diagonal', bilateral: false },

  // ── SHOULDERS — FRONT DELTS ───────────────────────────────────────────────
  { id: 'raise_front', name: 'Front Raise (Dumbbell)', primary_muscle: 'Front Delts', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: true },
  { id: 'raise_front_cable', name: 'Front Raise (Cable)', primary_muscle: 'Front Delts', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: false },
  { id: 'raise_front_barbell', name: 'Front Raise (Barbell)', primary_muscle: 'Front Delts', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Barbell', force_vector: 'diagonal', bilateral: true },
  { id: 'raise_front_plate', name: 'Front Raise (Plate)', primary_muscle: 'Front Delts', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Plate', force_vector: 'diagonal', bilateral: true },

  // ── SHOULDERS — SIDE DELTS ────────────────────────────────────────────────
  { id: 'raise_lateral', name: 'Lateral Raise (Dumbbell)', primary_muscle: 'Side Delts', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: true },
  { id: 'raise_lateral_cable', name: 'Lateral Raise (Cable)', primary_muscle: 'Side Delts', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: false },
  { id: 'raise_lateral_machine', name: 'Lateral Raise (Machine)', primary_muscle: 'Side Delts', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'upright_row_barbell', name: 'Upright Row (Barbell)', primary_muscle: 'Side Delts', secondary_muscle: 'Traps', movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'upright_row_cable', name: 'Upright Row (Cable)', primary_muscle: 'Side Delts', secondary_muscle: 'Traps', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'upright_row_dumbbell', name: 'Upright Row (Dumbbell)', primary_muscle: 'Side Delts', secondary_muscle: 'Traps', movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },

  // ── SHOULDERS — REAR DELTS ────────────────────────────────────────────────
  { id: 'fly_reverse', name: 'Reverse Fly (Dumbbell)', primary_muscle: 'Rear Delts', secondary_muscle: 'Upper Back', movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'horizontal', bilateral: true },
  { id: 'reverse_fly_machine', name: 'Reverse Fly (Machine)', primary_muscle: 'Rear Delts', secondary_muscle: 'Upper Back', movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'reverse_fly_cable', name: 'Reverse Fly (Cable)', primary_muscle: 'Rear Delts', secondary_muscle: 'Upper Back', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: true },

  // ── TRICEPS ───────────────────────────────────────────────────────────────
  { id: 'pushdown_tricep', name: 'Tricep Pushdown (Cable)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'pushdown_rope', name: 'Tricep Pushdown - Rope (Cable)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'pushdown_single', name: 'Single-Arm Tricep Pushdown (Cable)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Cable', force_vector: 'vertical', bilateral: false },
  { id: 'skullcrusher', name: 'Skull Crusher (Barbell)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'skullcrusher_ezbar', name: 'Skull Crusher (EZ-Bar)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'EZ-Bar', force_vector: 'vertical', bilateral: true },
  { id: 'closegrip_bench', name: 'Close-Grip Bench Press (Barbell)', primary_muscle: 'Triceps', secondary_muscle: 'Mid Chest', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'extension_overhead_tricep', name: 'Overhead Tricep Extension (Dumbbell)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'extension_overhead_cable', name: 'Overhead Tricep Extension (Cable)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'extension_overhead_barbell', name: 'Overhead Tricep Extension (Barbell)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'extension_overhead_ezbar', name: 'Overhead Tricep Extension (EZ-Bar)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'EZ-Bar', force_vector: 'vertical', bilateral: true },
  { id: 'dip', name: 'Tricep Dip', primary_muscle: 'Triceps', secondary_muscle: 'Mid Chest', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'bench_dip', name: 'Bench Dip', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'kickback_tricep', name: 'Tricep Kickback (Dumbbell)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'horizontal', bilateral: false },
  { id: 'kickback_cable', name: 'Tricep Kickback (Cable)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: false },

  // ── BICEPS ────────────────────────────────────────────────────────────────
  { id: 'curl_barbell', name: 'Curl (Barbell)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_ezbar', name: 'Curl (EZ-Bar)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'EZ-Bar', force_vector: 'vertical', bilateral: true },
  { id: 'curl_dumbbell', name: 'Curl (Dumbbell)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_cable', name: 'Curl (Cable)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'curl_cable_single', name: 'Single-Arm Curl (Cable)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: false },
  { id: 'curl_machine', name: 'Curl (Machine)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'curl_hammer', name: 'Hammer Curl (Dumbbell)', primary_muscle: 'Biceps', secondary_muscle: 'Forearms', movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_hammer_cable', name: 'Hammer Curl (Cable)', primary_muscle: 'Biceps', secondary_muscle: 'Forearms', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'curl_preacher', name: 'Preacher Curl (Machine)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'curl_preacher_barbell', name: 'Preacher Curl (Barbell)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'diagonal', bilateral: true },
  { id: 'curl_preacher_ezbar', name: 'Preacher Curl (EZ-Bar)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'EZ-Bar', force_vector: 'diagonal', bilateral: true },
  { id: 'curl_preacher_dumbbell', name: 'Preacher Curl (Dumbbell)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: false },
  { id: 'curl_incline', name: 'Incline Curl (Dumbbell)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: true },
  { id: 'curl_concentration', name: 'Concentration Curl (Dumbbell)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'curl_spider', name: 'Spider Curl (Barbell)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_reverse', name: 'Reverse Curl (Barbell)', primary_muscle: 'Biceps', secondary_muscle: 'Forearms', movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_zottman', name: 'Zottman Curl (Dumbbell)', primary_muscle: 'Biceps', secondary_muscle: 'Forearms', movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_cross_body', name: 'Cross-Body Curl (Dumbbell)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: false },

  // ── QUADS ─────────────────────────────────────────────────────────────────
  { id: 'squat_barbell', name: 'Squat (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'squat_front', name: 'Front Squat (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'squat_box', name: 'Box Squat (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'squat_zercher', name: 'Zercher Squat (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'smith_squat', name: 'Squat (Smith Machine)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Smith Machine', force_vector: 'vertical', bilateral: true },
  { id: 'squat_goblet', name: 'Goblet Squat (Dumbbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'squat_goblet_kettlebell', name: 'Goblet Squat (Kettlebell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: true },
  { id: 'leg_press', name: 'Leg Press (Machine)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'leg_press_single', name: 'Single-Leg Press (Machine)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: false },
  { id: 'hack_squat', name: 'Hack Squat (Machine)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'squat_belt', name: 'Belt Squat', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'sissy_squat', name: 'Sissy Squat', primary_muscle: 'Quads', secondary_muscle: null, movement_pattern: 'Squat', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: true },
  { id: 'extension_leg', name: 'Leg Extension (Machine)', primary_muscle: 'Quads', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'extension_leg_single', name: 'Single-Leg Extension (Machine)', primary_muscle: 'Quads', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: false },
  { id: 'lunge_barbell', name: 'Lunge (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: false },
  { id: 'lunge_dumbbell', name: 'Lunge (Dumbbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'lunge_walking', name: 'Walking Lunge (Dumbbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'lunge_reverse', name: 'Reverse Lunge (Dumbbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'lunge_lateral', name: 'Lateral Lunge (Dumbbell)', primary_muscle: 'Quads', secondary_muscle: 'Adductors', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: false },
  { id: 'split_squat_bulgarian', name: 'Bulgarian Split Squat (Dumbbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'split_squat_bulgarian_barbell', name: 'Bulgarian Split Squat (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: false },
  { id: 'step_up', name: 'Step-Up (Dumbbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'step_up_barbell', name: 'Step-Up (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: false },
  { id: 'jump_squat', name: 'Jump Squat', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },

  // ── HAMSTRINGS ────────────────────────────────────────────────────────────
  { id: 'rdl', name: 'Romanian Deadlift (Barbell)', primary_muscle: 'Hamstrings', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'rdl_dumbbell', name: 'Romanian Deadlift (Dumbbell)', primary_muscle: 'Hamstrings', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'rdl_single', name: 'Single-Leg Romanian Deadlift (Dumbbell)', primary_muscle: 'Hamstrings', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'rdl_cable', name: 'Romanian Deadlift (Cable)', primary_muscle: 'Hamstrings', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'rdl_kettlebell', name: 'Romanian Deadlift (Kettlebell)', primary_muscle: 'Hamstrings', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_lying', name: 'Lying Leg Curl (Machine)', primary_muscle: 'Hamstrings', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'curl_seated', name: 'Seated Leg Curl (Machine)', primary_muscle: 'Hamstrings', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'curl_standing', name: 'Standing Leg Curl (Machine)', primary_muscle: 'Hamstrings', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: false },
  { id: 'nordic_curl', name: 'Nordic Curl', primary_muscle: 'Hamstrings', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'glute_ham_raise', name: 'Glute-Ham Raise', primary_muscle: 'Hamstrings', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },

  // ── GLUTES ────────────────────────────────────────────────────────────────
  { id: 'hip_thrust', name: 'Hip Thrust (Barbell)', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'hip_thrust_dumbbell', name: 'Hip Thrust (Dumbbell)', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'smith_hip_thrust', name: 'Hip Thrust (Smith Machine)', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Smith Machine', force_vector: 'vertical', bilateral: true },
  { id: 'hip_thrust_machine', name: 'Hip Thrust (Machine)', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'glute_bridge', name: 'Glute Bridge', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'glute_bridge_single', name: 'Single-Leg Glute Bridge', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: false },
  { id: 'kickback_glute', name: 'Glute Kickback (Cable)', primary_muscle: 'Glutes', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: false },
  { id: 'donkey_kick', name: 'Donkey Kick', primary_muscle: 'Glutes', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: false },
  { id: 'fire_hydrant', name: 'Fire Hydrant', primary_muscle: 'Glutes', secondary_muscle: 'Abductors', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: false },
  { id: 'squat_sumo_dumbbell', name: 'Sumo Squat (Dumbbell)', primary_muscle: 'Glutes', secondary_muscle: 'Adductors', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },

  // ── CALVES ────────────────────────────────────────────────────────────────
  { id: 'raise_calf_standing', name: 'Calf Raise - Standing (Machine)', primary_muscle: 'Calves', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'raise_calf_seated', name: 'Calf Raise - Seated (Machine)', primary_muscle: 'Calves', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'raise_calf_leg_press', name: 'Calf Raise - Leg Press (Machine)', primary_muscle: 'Calves', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'raise_calf_smith', name: 'Calf Raise (Smith Machine)', primary_muscle: 'Calves', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Smith Machine', force_vector: 'vertical', bilateral: true },
  { id: 'raise_calf_barbell', name: 'Calf Raise (Barbell)', primary_muscle: 'Calves', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'raise_calf_dumbbell', name: 'Single-Leg Calf Raise (Dumbbell)', primary_muscle: 'Calves', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'raise_calf_bodyweight', name: 'Calf Raise (Bodyweight)', primary_muscle: 'Calves', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },

  // ── ADDUCTORS ─────────────────────────────────────────────────────────────
  { id: 'adductor_machine', name: 'Hip Adduction (Machine)', primary_muscle: 'Adductors', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'cable_adduction', name: 'Hip Adduction (Cable)', primary_muscle: 'Adductors', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: false },
  { id: 'copenhagen_plank', name: 'Copenhagen Plank', primary_muscle: 'Adductors', secondary_muscle: 'Core', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: false },

  // ── ABDUCTORS ─────────────────────────────────────────────────────────────
  { id: 'abduction_machine', name: 'Hip Abduction (Machine)', primary_muscle: 'Abductors', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'cable_abduction', name: 'Hip Abduction (Cable)', primary_muscle: 'Abductors', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: false },
  { id: 'clamshell', name: 'Clamshell', primary_muscle: 'Abductors', secondary_muscle: 'Glutes', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: false },

  // ── HIP FLEXORS ───────────────────────────────────────────────────────────
  { id: 'hip_flexor_raise', name: 'Hip Flexor Raise', primary_muscle: 'Hip Flexors', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: false },
  { id: 'cable_hip_flexion', name: 'Hip Flexion (Cable)', primary_muscle: 'Hip Flexors', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: false },
  { id: 'psoas_march', name: 'Psoas March', primary_muscle: 'Hip Flexors', secondary_muscle: 'Core', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: false },

  // ── CORE ──────────────────────────────────────────────────────────────────
  { id: 'plank', name: 'Plank', primary_muscle: 'Core', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'ab_rollout', name: 'Ab Wheel Rollout', primary_muscle: 'Core', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'ab_rollout_barbell', name: 'Ab Rollout (Barbell)', primary_muscle: 'Core', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'pallof_press', name: 'Pallof Press (Cable)', primary_muscle: 'Core', secondary_muscle: 'Obliques', movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: false },
  { id: 'dead_bug', name: 'Dead Bug', primary_muscle: 'Core', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'hollow_body', name: 'Hollow Body Hold', primary_muscle: 'Core', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'l_sit', name: 'L-Sit', primary_muscle: 'Core', secondary_muscle: 'Hip Flexors', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },

  // Abs
  { id: 'crunch', name: 'Crunch', primary_muscle: 'Abs', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'crunch_machine', name: 'Crunch (Machine)', primary_muscle: 'Abs', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'cable_crunch', name: 'Cable Crunch', primary_muscle: 'Abs', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: true },
  { id: 'decline_crunch', name: 'Decline Crunch', primary_muscle: 'Abs', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: true },
  { id: 'bicycle_crunch', name: 'Bicycle Crunch', primary_muscle: 'Abs', secondary_muscle: 'Obliques', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'reverse_crunch', name: 'Reverse Crunch', primary_muscle: 'Abs', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'situp', name: 'Sit-Up', primary_muscle: 'Abs', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'leg_raise', name: 'Leg Raise', primary_muscle: 'Abs', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'hanging_leg_raise', name: 'Hanging Leg Raise', primary_muscle: 'Abs', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'toes_to_bar', name: 'Toes-to-Bar', primary_muscle: 'Abs', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'dragon_flag', name: 'Dragon Flag', primary_muscle: 'Abs', secondary_muscle: 'Core', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'v_up', name: 'V-Up', primary_muscle: 'Abs', secondary_muscle: 'Hip Flexors', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },

  // Obliques
  { id: 'russian_twist', name: 'Russian Twist', primary_muscle: 'Obliques', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'cable_woodchop', name: 'Woodchop (Cable)', primary_muscle: 'Obliques', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: false },
  { id: 'side_plank', name: 'Side Plank', primary_muscle: 'Obliques', secondary_muscle: 'Core', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: false },
  { id: 'oblique_crunch', name: 'Oblique Crunch', primary_muscle: 'Obliques', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: false },
  { id: 'landmine_twist', name: 'Landmine Rotation', primary_muscle: 'Obliques', secondary_muscle: 'Core', movement_pattern: 'Isolation', equipment_type: 'Landmine', force_vector: 'diagonal', bilateral: false },

  // ── TRAPS ─────────────────────────────────────────────────────────────────
  { id: 'shrug_barbell', name: 'Shrug (Barbell)', primary_muscle: 'Traps', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'shrug_dumbbell', name: 'Shrug (Dumbbell)', primary_muscle: 'Traps', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'shrug_cable', name: 'Shrug (Cable)', primary_muscle: 'Traps', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'shrug_smith', name: 'Shrug (Smith Machine)', primary_muscle: 'Traps', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Smith Machine', force_vector: 'vertical', bilateral: true },
  { id: 'shrug_trap_bar', name: 'Shrug (Trap Bar)', primary_muscle: 'Traps', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Trap Bar', force_vector: 'vertical', bilateral: true },
  { id: 'high_pull', name: 'High Pull (Barbell)', primary_muscle: 'Traps', secondary_muscle: 'Shoulders', movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },

  // ── FOREARMS ──────────────────────────────────────────────────────────────
  { id: 'curl_wrist', name: 'Wrist Curl (Barbell)', primary_muscle: 'Forearms', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'extension_wrist', name: 'Wrist Extension (Barbell)', primary_muscle: 'Forearms', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'farmers_carry', name: "Farmer's Carry (Dumbbell)", primary_muscle: 'Forearms', secondary_muscle: 'Traps', movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'farmers_carry_barbell', name: "Farmer's Carry (Barbell)", primary_muscle: 'Forearms', secondary_muscle: 'Traps', movement_pattern: 'Isolation', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'plate_pinch', name: 'Plate Pinch', primary_muscle: 'Forearms', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Plate', force_vector: 'vertical', bilateral: false },
  { id: 'reverse_curl_dumbbell', name: 'Reverse Curl (Dumbbell)', primary_muscle: 'Forearms', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },

  // ── NECK ──────────────────────────────────────────────────────────────────
  { id: 'neck_curl', name: 'Neck Curl', primary_muscle: 'Neck', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: true },
  { id: 'neck_extension', name: 'Neck Extension', primary_muscle: 'Neck', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: true },
  { id: 'neck_lateral_flex', name: 'Neck Lateral Flexion', primary_muscle: 'Neck', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: false },

  // ── TIBIALIS ──────────────────────────────────────────────────────────────
  { id: 'tib_raise', name: 'Tib Raise', primary_muscle: 'Tibialis', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'tib_bar_raise', name: 'Tib Bar Raise', primary_muscle: 'Tibialis', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },

  // ── OLYMPIC / POWER ───────────────────────────────────────────────────────
  { id: 'power_clean', name: 'Power Clean (Barbell)', primary_muscle: 'Traps', secondary_muscle: 'Quads', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'hang_clean', name: 'Hang Clean (Barbell)', primary_muscle: 'Traps', secondary_muscle: 'Quads', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'power_snatch', name: 'Power Snatch (Barbell)', primary_muscle: 'Traps', secondary_muscle: 'Quads', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'clean_jerk', name: 'Clean and Jerk (Barbell)', primary_muscle: 'Traps', secondary_muscle: 'Shoulders', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'push_jerk', name: 'Push Jerk (Barbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Quads', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'hang_snatch', name: 'Hang Snatch (Barbell)', primary_muscle: 'Traps', secondary_muscle: 'Quads', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },

  // ── CONDITIONING / FULL BODY ──────────────────────────────────────────────
  { id: 'kettlebell_swing', name: 'Kettlebell Swing', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: true },
  { id: 'kettlebell_clean', name: 'Kettlebell Clean', primary_muscle: 'Traps', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: false },
  { id: 'kettlebell_press', name: 'Kettlebell Press', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: false },
  { id: 'turkish_getup', name: 'Turkish Get-Up (Kettlebell)', primary_muscle: 'Shoulders', secondary_muscle: 'Core', movement_pattern: 'Push', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: false },
  { id: 'box_jump', name: 'Box Jump', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'burpee', name: 'Burpee', primary_muscle: 'Quads', secondary_muscle: 'Mid Chest', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'thruster', name: 'Thruster (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Shoulders', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'thruster_dumbbell', name: 'Thruster (Dumbbell)', primary_muscle: 'Quads', secondary_muscle: 'Shoulders', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'sled_push', name: 'Sled Push', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Push', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'battle_ropes', name: 'Battle Ropes', primary_muscle: 'Shoulders', secondary_muscle: 'Core', movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'jump_rope', name: 'Jump Rope', primary_muscle: 'Calves', secondary_muscle: 'Quads', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'rowing_ergometer', name: 'Rowing (Ergometer)', primary_muscle: 'Upper Back', secondary_muscle: 'Quads', movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'bench_close_grip_smith', name: 'Close-Grip Bench Press (Smith Machine)', primary_muscle: 'Triceps', secondary_muscle: 'Mid Chest', movement_pattern: 'Push', equipment_type: 'Smith Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'bench_wide_grip_barbell', name: 'Wide-Grip Bench Press (Barbell)', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'bench_pause_barbell', name: 'Paused Bench Press (Barbell)', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'bench_floor_barbell', name: 'Floor Press (Barbell)', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'bench_floor_dumbbell', name: 'Floor Press (Dumbbell)', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'horizontal', bilateral: true },
  { id: 'chest_press_incline_plate', name: 'Incline Chest Press (Machine)', primary_muscle: 'Upper Chest', secondary_muscle: 'Shoulders', movement_pattern: 'Push', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'chest_press_decline_machine', name: 'Decline Chest Press (Machine)', primary_muscle: 'Lower Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'chest_press_single_arm_machine', name: 'Single-Arm Chest Press (Machine)', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: false },
  { id: 'fly_machine', name: 'Fly (Machine)', primary_muscle: 'Mid Chest', secondary_muscle: null, movement_pattern: 'Fly', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'fly_low_to_high_cable', name: 'Low-to-High Fly (Cable)', primary_muscle: 'Upper Chest', secondary_muscle: null, movement_pattern: 'Fly', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: true },
  { id: 'fly_high_to_low_cable', name: 'High-to-Low Fly (Cable)', primary_muscle: 'Lower Chest', secondary_muscle: null, movement_pattern: 'Fly', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: true },
  { id: 'press_around_cable', name: 'Press Around (Cable)', primary_muscle: 'Mid Chest', secondary_muscle: null, movement_pattern: 'Fly', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: false },
  { id: 'pullover_dumbbell_chest', name: 'Pullover (Dumbbell)', primary_muscle: 'Mid Chest', secondary_muscle: 'Lats', movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: true },
  { id: 'pushup_close_grip', name: 'Close-Grip Push-Up', primary_muscle: 'Triceps', secondary_muscle: 'Mid Chest', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'pushup_deficit', name: 'Deficit Push-Up', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'pushup_weighted', name: 'Weighted Push-Up', primary_muscle: 'Mid Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'dip_weighted_chest', name: 'Weighted Chest Dip', primary_muscle: 'Lower Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'bench_decline_machine', name: 'Decline Bench Press (Machine)', primary_muscle: 'Lower Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: true },
  { id: 'bench_incline_close_grip_barbell', name: 'Close-Grip Incline Press (Barbell)', primary_muscle: 'Upper Chest', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'diagonal', bilateral: true },
  { id: 'bench_guillotine_barbell', name: 'Guillotine Press (Barbell)', primary_muscle: 'Upper Chest', secondary_muscle: 'Shoulders', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },

  { id: 'pullup_weighted', name: 'Weighted Pull-Up', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'chinup_weighted', name: 'Weighted Chin-Up', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'pullup_assisted_machine', name: 'Assisted Pull-Up (Machine)', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'chinup_assisted_machine', name: 'Assisted Chin-Up (Machine)', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'lat_pulldown_reverse_grip', name: 'Reverse-Grip Lat Pulldown (Cable)', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'lat_pulldown_single_arm', name: 'Single-Arm Lat Pulldown (Cable)', primary_muscle: 'Lats', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: false },
  { id: 'row_chest_supported_neutral_machine', name: 'Neutral-Grip Chest-Supported Row (Machine)', primary_muscle: 'Upper Back', secondary_muscle: 'Lats', movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'row_chest_supported_dumbbell', name: 'Chest-Supported Row (Dumbbell)', primary_muscle: 'Upper Back', secondary_muscle: 'Lats', movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'horizontal', bilateral: true },
  { id: 'row_seal_barbell', name: 'Seal Row (Barbell)', primary_muscle: 'Upper Back', secondary_muscle: 'Lats', movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'row_meadows_landmine', name: 'Meadows Row (Landmine)', primary_muscle: 'Lats', secondary_muscle: 'Upper Back', movement_pattern: 'Pull', equipment_type: 'Landmine', force_vector: 'horizontal', bilateral: false },
  { id: 'row_landmine', name: 'Landmine Row', primary_muscle: 'Upper Back', secondary_muscle: 'Lats', movement_pattern: 'Pull', equipment_type: 'Landmine', force_vector: 'horizontal', bilateral: true },
  { id: 'row_tbar_machine', name: 'T-Bar Row (Machine)', primary_muscle: 'Upper Back', secondary_muscle: 'Lats', movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'row_tbar_landmine', name: 'T-Bar Row (Landmine)', primary_muscle: 'Upper Back', secondary_muscle: 'Lats', movement_pattern: 'Pull', equipment_type: 'Landmine', force_vector: 'horizontal', bilateral: true },
  { id: 'row_high_cable', name: 'High Row (Cable)', primary_muscle: 'Upper Back', secondary_muscle: 'Lats', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: true },
  { id: 'row_low_cable', name: 'Low Row (Cable)', primary_muscle: 'Lats', secondary_muscle: 'Upper Back', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: true },
  { id: 'row_inverted_weighted', name: 'Weighted Inverted Row', primary_muscle: 'Upper Back', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'pullover_single_arm_cable', name: 'Single-Arm Pullover (Cable)', primary_muscle: 'Lats', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: false },
  { id: 'pullover_single_arm_machine', name: 'Single-Arm Pullover (Machine)', primary_muscle: 'Lats', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: false },
  { id: 'deadlift_deficit_barbell', name: 'Deficit Deadlift (Barbell)', primary_muscle: 'Lower Back', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'deadlift_snatch_grip_barbell', name: 'Snatch-Grip Deadlift (Barbell)', primary_muscle: 'Lower Back', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'deadlift_sumo_block_barbell', name: 'Block Pull (Barbell)', primary_muscle: 'Lower Back', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'good_morning_smith', name: 'Good Morning (Smith Machine)', primary_muscle: 'Lower Back', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Smith Machine', force_vector: 'vertical', bilateral: true },
  { id: 'back_extension_weighted', name: 'Weighted Back Extension', primary_muscle: 'Lower Back', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: true },
  { id: 'reverse_hyper_machine', name: 'Reverse Hyperextension (Machine)', primary_muscle: 'Lower Back', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'scapular_pullup', name: 'Scapular Pull-Up', primary_muscle: 'Lats', secondary_muscle: 'Traps', movement_pattern: 'Pull', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },

  { id: 'shoulder_press_single_arm_dumbbell', name: 'Single-Arm Shoulder Press (Dumbbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'shoulder_press_seated_barbell', name: 'Seated Shoulder Press (Barbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'shoulder_press_seated_dumbbell', name: 'Seated Shoulder Press (Dumbbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'shoulder_press_machine_neutral', name: 'Neutral-Grip Shoulder Press (Machine)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'arnold_press_seated', name: 'Seated Arnold Press (Dumbbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'raise_lateral_leaning_cable', name: 'Leaning Lateral Raise (Cable)', primary_muscle: 'Side Delts', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: false },
  { id: 'raise_lateral_leaning_dumbbell', name: 'Leaning Lateral Raise (Dumbbell)', primary_muscle: 'Side Delts', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: false },
  { id: 'raise_lateral_seated_dumbbell', name: 'Seated Lateral Raise (Dumbbell)', primary_muscle: 'Side Delts', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'raise_front_two_plate', name: 'Two-Plate Front Raise', primary_muscle: 'Front Delts', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Plate', force_vector: 'vertical', bilateral: true },
  { id: 'raise_front_rope_cable', name: 'Front Raise (Cable Rope)', primary_muscle: 'Front Delts', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'raise_y_cable', name: 'Y Raise (Cable)', primary_muscle: 'Rear Delts', secondary_muscle: 'Traps', movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: true },
  { id: 'raise_y_incline_dumbbell', name: 'Incline Y Raise (Dumbbell)', primary_muscle: 'Rear Delts', secondary_muscle: 'Traps', movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'diagonal', bilateral: true },
  { id: 'face_pull_rope', name: 'Face Pull (Cable Rope)', primary_muscle: 'Rear Delts', secondary_muscle: 'Traps', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: true },
  { id: 'rear_delt_row_dumbbell', name: 'Rear Delt Row (Dumbbell)', primary_muscle: 'Rear Delts', secondary_muscle: 'Upper Back', movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'horizontal', bilateral: true },
  { id: 'upright_row_smith', name: 'Upright Row (Smith Machine)', primary_muscle: 'Side Delts', secondary_muscle: 'Traps', movement_pattern: 'Pull', equipment_type: 'Smith Machine', force_vector: 'vertical', bilateral: true },
  { id: 'shrug_single_arm_smith', name: 'Single-Arm Shrug (Smith Machine)', primary_muscle: 'Traps', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Smith Machine', force_vector: 'vertical', bilateral: false },
  { id: 'shrug_behind_back_barbell', name: 'Behind-the-Back Shrug (Barbell)', primary_muscle: 'Traps', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'press_z_barbell', name: 'Z Press (Barbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'press_z_dumbbell', name: 'Z Press (Dumbbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Triceps', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },

  { id: 'triceps_pushdown_vbar', name: 'Tricep Pushdown (V-Bar)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'triceps_pushdown_single_arm_cable', name: 'Single-Arm Tricep Pushdown (Cable)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Cable', force_vector: 'vertical', bilateral: false },
  { id: 'triceps_extension_cross_body_cable', name: 'Cross-Body Tricep Extension (Cable)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: false },
  { id: 'triceps_extension_lying_dumbbell', name: 'Lying Tricep Extension (Dumbbell)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'triceps_extension_incline_ezbar', name: 'Incline Tricep Extension (EZ-Bar)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'EZ-Bar', force_vector: 'diagonal', bilateral: true },
  { id: 'triceps_extension_machine', name: 'Tricep Extension (Machine)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'triceps_dip_assisted_machine', name: 'Assisted Tricep Dip (Machine)', primary_muscle: 'Triceps', secondary_muscle: 'Lower Chest', movement_pattern: 'Push', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'triceps_dip_weighted', name: 'Weighted Tricep Dip', primary_muscle: 'Triceps', secondary_muscle: 'Lower Chest', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'jm_press_barbell', name: 'JM Press (Barbell)', primary_muscle: 'Triceps', secondary_muscle: 'Mid Chest', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'tate_press_dumbbell', name: 'Tate Press (Dumbbell)', primary_muscle: 'Triceps', secondary_muscle: null, movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },

  { id: 'curl_spider_barbell', name: 'Spider Curl (Barbell)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_spider_dumbbell', name: 'Spider Curl (Dumbbell)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_spider_ezbar', name: 'Spider Curl (EZ-Bar)', primary_muscle: 'Biceps', secondary_muscle: null, movement_pattern: 'Pull', equipment_type: 'EZ-Bar', force_vector: 'vertical', bilateral: true },
  { id: 'curl_drag_barbell', name: 'Drag Curl (Barbell)', primary_muscle: 'Biceps', secondary_muscle: 'Forearms', movement_pattern: 'Pull', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_drag_smith', name: 'Drag Curl (Smith Machine)', primary_muscle: 'Biceps', secondary_muscle: 'Forearms', movement_pattern: 'Pull', equipment_type: 'Smith Machine', force_vector: 'vertical', bilateral: true },
  { id: 'curl_waiter_dumbbell', name: 'Waiter Curl (Dumbbell)', primary_muscle: 'Biceps', secondary_muscle: 'Forearms', movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_zottman_dumbbell', name: 'Zottman Curl (Dumbbell)', primary_muscle: 'Biceps', secondary_muscle: 'Forearms', movement_pattern: 'Pull', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_reverse_ezbar', name: 'Reverse Curl (EZ-Bar)', primary_muscle: 'Forearms', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'EZ-Bar', force_vector: 'vertical', bilateral: true },
  { id: 'curl_reverse_cable', name: 'Reverse Curl (Cable)', primary_muscle: 'Forearms', secondary_muscle: 'Biceps', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },
  { id: 'curl_wrist_barbell', name: 'Wrist Curl (Barbell)', primary_muscle: 'Forearms', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_wrist_dumbbell', name: 'Wrist Curl (Dumbbell)', primary_muscle: 'Forearms', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_wrist_reverse_barbell', name: 'Reverse Wrist Curl (Barbell)', primary_muscle: 'Forearms', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_wrist_reverse_dumbbell', name: 'Reverse Wrist Curl (Dumbbell)', primary_muscle: 'Forearms', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'curl_cable_rope', name: 'Hammer Curl (Cable Rope)', primary_muscle: 'Biceps', secondary_muscle: 'Forearms', movement_pattern: 'Pull', equipment_type: 'Cable', force_vector: 'vertical', bilateral: true },

  { id: 'squat_pause_barbell', name: 'Paused Squat (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'squat_pin_barbell', name: 'Pin Squat (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'squat_safety_bar', name: 'Safety Bar Squat', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'squat_zercher_barbell', name: 'Zercher Squat (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'squat_landmine', name: 'Landmine Squat', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Landmine', force_vector: 'vertical', bilateral: true },
  { id: 'squat_cyclist_dumbbell', name: 'Cyclist Squat (Dumbbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'split_squat_barbell', name: 'Split Squat (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: false },
  { id: 'split_squat_smith', name: 'Split Squat (Smith Machine)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Smith Machine', force_vector: 'vertical', bilateral: false },
  { id: 'bulgarian_split_squat_smith', name: 'Bulgarian Split Squat (Smith Machine)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Smith Machine', force_vector: 'vertical', bilateral: false },
  { id: 'bulgarian_split_squat_bodyweight', name: 'Bulgarian Split Squat', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: false },
  { id: 'lunge_reverse_barbell', name: 'Reverse Lunge (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: false },
  { id: 'lunge_reverse_dumbbell', name: 'Reverse Lunge (Dumbbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'lunge_walking_barbell', name: 'Walking Lunge (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: false },
  { id: 'lunge_walking_dumbbell', name: 'Walking Lunge (Dumbbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'lunge_curtsy_dumbbell', name: 'Curtsy Lunge (Dumbbell)', primary_muscle: 'Glutes', secondary_muscle: 'Quads', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'stepup_barbell', name: 'Step-Up (Barbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: false },
  { id: 'stepup_bodyweight', name: 'Step-Up', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: false },
  { id: 'leg_press_single_leg_machine', name: 'Single-Leg Leg Press (Machine)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: false },
  { id: 'leg_press_vertical_machine', name: 'Vertical Leg Press (Machine)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'hack_squat_reverse_machine', name: 'Reverse Hack Squat (Machine)', primary_muscle: 'Glutes', secondary_muscle: 'Quads', movement_pattern: 'Squat', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'pendulum_squat_machine', name: 'Pendulum Squat (Machine)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'v_squat_machine', name: 'V-Squat (Machine)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'extension_leg_single_leg_machine', name: 'Single-Leg Extension (Machine)', primary_muscle: 'Quads', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'vertical', bilateral: false },
  { id: 'curl_leg_single_leg_machine', name: 'Single-Leg Curl (Machine)', primary_muscle: 'Hamstrings', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'vertical', bilateral: false },
  { id: 'curl_leg_standing_machine', name: 'Standing Leg Curl (Machine)', primary_muscle: 'Hamstrings', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'vertical', bilateral: false },
  { id: 'rdl_single_leg_barbell', name: 'Single-Leg Romanian Deadlift (Barbell)', primary_muscle: 'Hamstrings', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: false },
  { id: 'rdl_single_leg_dumbbell', name: 'Single-Leg Romanian Deadlift (Dumbbell)', primary_muscle: 'Hamstrings', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'rdl_b_stance_barbell', name: 'B-Stance Romanian Deadlift (Barbell)', primary_muscle: 'Hamstrings', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: false },
  { id: 'rdl_b_stance_dumbbell', name: 'B-Stance Romanian Deadlift (Dumbbell)', primary_muscle: 'Hamstrings', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'hip_thrust_smith', name: 'Hip Thrust (Smith Machine)', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Smith Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'hip_thrust_single_leg_bodyweight', name: 'Single-Leg Hip Thrust', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: false },
  { id: 'glute_bridge_barbell', name: 'Glute Bridge (Barbell)', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'horizontal', bilateral: true },
  { id: 'glute_bridge_bodyweight', name: 'Glute Bridge', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'kickback_glute_machine', name: 'Glute Kickback (Machine)', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: false },
  { id: 'abduction_standing_cable', name: 'Standing Hip Abduction (Cable)', primary_muscle: 'Abductors', secondary_muscle: 'Glutes', movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: false },
  { id: 'adduction_standing_cable', name: 'Standing Hip Adduction (Cable)', primary_muscle: 'Adductors', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: false },
  { id: 'calf_raise_donkey_machine', name: 'Donkey Calf Raise (Machine)', primary_muscle: 'Calves', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'calf_raise_leg_press_machine', name: 'Calf Press (Machine)', primary_muscle: 'Calves', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },
  { id: 'calf_raise_single_leg_bodyweight', name: 'Single-Leg Calf Raise', primary_muscle: 'Calves', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: false },
  { id: 'tib_raise_machine', name: 'Tib Raise (Machine)', primary_muscle: 'Tibialis', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'vertical', bilateral: true },

  { id: 'crunch_rotary_machine', name: 'Rotary Crunch (Machine)', primary_muscle: 'Obliques', secondary_muscle: 'Abs', movement_pattern: 'Isolation', equipment_type: 'Machine', force_vector: 'diagonal', bilateral: false },
  { id: 'crunch_weighted', name: 'Weighted Crunch', primary_muscle: 'Abs', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: true },
  { id: 'situp_weighted', name: 'Weighted Sit-Up', primary_muscle: 'Abs', secondary_muscle: 'Hip Flexors', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: true },
  { id: 'situp_decline_weighted', name: 'Weighted Decline Sit-Up', primary_muscle: 'Abs', secondary_muscle: 'Hip Flexors', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'diagonal', bilateral: true },
  { id: 'leg_raise_captains_chair', name: "Captain's Chair Leg Raise", primary_muscle: 'Abs', secondary_muscle: 'Hip Flexors', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'knee_raise_hanging', name: 'Hanging Knee Raise', primary_muscle: 'Abs', secondary_muscle: 'Hip Flexors', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'toes_to_bar_strict', name: 'Strict Toes-to-Bar', primary_muscle: 'Abs', secondary_muscle: 'Lats', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'dragon_flag_negative', name: 'Negative Dragon Flag', primary_muscle: 'Abs', secondary_muscle: 'Lats', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'dead_bug_weighted', name: 'Weighted Dead Bug', primary_muscle: 'Core', secondary_muscle: null, movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: false },
  { id: 'hollow_hold', name: 'Hollow Hold', primary_muscle: 'Core', secondary_muscle: 'Abs', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'plank_weighted', name: 'Weighted Plank', primary_muscle: 'Core', secondary_muscle: 'Abs', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'side_plank_weighted', name: 'Weighted Side Plank', primary_muscle: 'Obliques', secondary_muscle: 'Core', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: false },
  { id: 'woodchop_high_to_low_cable', name: 'High-to-Low Wood Chop (Cable)', primary_muscle: 'Obliques', secondary_muscle: 'Core', movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: false },
  { id: 'woodchop_low_to_high_cable', name: 'Low-to-High Wood Chop (Cable)', primary_muscle: 'Obliques', secondary_muscle: 'Core', movement_pattern: 'Isolation', equipment_type: 'Cable', force_vector: 'diagonal', bilateral: false },
  { id: 'russian_twist_plate', name: 'Russian Twist (Plate)', primary_muscle: 'Obliques', secondary_muscle: 'Abs', movement_pattern: 'Isolation', equipment_type: 'Plate', force_vector: 'horizontal', bilateral: true },
  { id: 'russian_twist_medicine_ball', name: 'Russian Twist (Dumbbell)', primary_muscle: 'Obliques', secondary_muscle: 'Abs', movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'horizontal', bilateral: true },
  { id: 'pallof_press_tall_kneeling', name: 'Tall-Kneeling Pallof Press (Cable)', primary_muscle: 'Obliques', secondary_muscle: 'Core', movement_pattern: 'Push', equipment_type: 'Cable', force_vector: 'horizontal', bilateral: false },
  { id: 'ab_wheel_kneeling', name: 'Kneeling Ab Wheel Rollout', primary_muscle: 'Abs', secondary_muscle: 'Lats', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },
  { id: 'ab_wheel_standing', name: 'Standing Ab Wheel Rollout', primary_muscle: 'Abs', secondary_muscle: 'Lats', movement_pattern: 'Isolation', equipment_type: 'Bodyweight', force_vector: 'horizontal', bilateral: true },

  { id: 'clean_pull_barbell', name: 'Clean Pull (Barbell)', primary_muscle: 'Traps', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'snatch_pull_barbell', name: 'Snatch Pull (Barbell)', primary_muscle: 'Traps', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'muscle_clean_barbell', name: 'Muscle Clean (Barbell)', primary_muscle: 'Traps', secondary_muscle: 'Shoulders', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'split_jerk_barbell', name: 'Split Jerk (Barbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Quads', movement_pattern: 'Push', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'power_clean_hang_high_barbell', name: 'High Hang Power Clean (Barbell)', primary_muscle: 'Traps', secondary_muscle: 'Quads', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },
  { id: 'power_snatch_hang_high_barbell', name: 'High Hang Power Snatch (Barbell)', primary_muscle: 'Traps', secondary_muscle: 'Quads', movement_pattern: 'Hinge', equipment_type: 'Barbell', force_vector: 'vertical', bilateral: true },

  { id: 'farmers_walk_dumbbell', name: "Farmer's Walk (Dumbbell)", primary_muscle: 'Forearms', secondary_muscle: 'Traps', movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'farmers_walk_kettlebell', name: "Farmer's Walk (Kettlebell)", primary_muscle: 'Forearms', secondary_muscle: 'Traps', movement_pattern: 'Isolation', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: true },
  { id: 'suitcase_carry_dumbbell', name: 'Suitcase Carry (Dumbbell)', primary_muscle: 'Obliques', secondary_muscle: 'Forearms', movement_pattern: 'Isolation', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'suitcase_carry_kettlebell', name: 'Suitcase Carry (Kettlebell)', primary_muscle: 'Obliques', secondary_muscle: 'Forearms', movement_pattern: 'Isolation', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: false },
  { id: 'overhead_carry_dumbbell', name: 'Overhead Carry (Dumbbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Core', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false },
  { id: 'overhead_carry_kettlebell', name: 'Overhead Carry (Kettlebell)', primary_muscle: 'Shoulders', secondary_muscle: 'Core', movement_pattern: 'Push', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: false },
  { id: 'sled_drag_backward', name: 'Backward Sled Drag', primary_muscle: 'Quads', secondary_muscle: 'Calves', movement_pattern: 'Squat', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'sled_pull_rope', name: 'Sled Pull', primary_muscle: 'Upper Back', secondary_muscle: 'Quads', movement_pattern: 'Pull', equipment_type: 'Machine', force_vector: 'horizontal', bilateral: true },
  { id: 'wall_ball', name: 'Wall Ball', primary_muscle: 'Quads', secondary_muscle: 'Shoulders', movement_pattern: 'Push', equipment_type: 'Bodyweight', force_vector: 'vertical', bilateral: true },
  { id: 'devil_press_dumbbell', name: "Devil's Press (Dumbbell)", primary_muscle: 'Shoulders', secondary_muscle: 'Glutes', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'man_maker_dumbbell', name: 'Man Maker (Dumbbell)', primary_muscle: 'Shoulders', secondary_muscle: 'Quads', movement_pattern: 'Push', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: true },
  { id: 'clean_press_kettlebell', name: 'Clean and Press (Kettlebell)', primary_muscle: 'Shoulders', secondary_muscle: 'Glutes', movement_pattern: 'Push', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: false },
  { id: 'snatch_kettlebell', name: 'Snatch (Kettlebell)', primary_muscle: 'Shoulders', secondary_muscle: 'Glutes', movement_pattern: 'Hinge', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: false },
  { id: 'swing_single_arm_kettlebell', name: 'Single-Arm Kettlebell Swing', primary_muscle: 'Glutes', secondary_muscle: 'Hamstrings', movement_pattern: 'Hinge', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: false },
  { id: 'goblet_lunge_kettlebell', name: 'Goblet Lunge (Kettlebell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Kettlebell', force_vector: 'vertical', bilateral: false },
  { id: 'box_step_over_dumbbell', name: 'Box Step-Over (Dumbbell)', primary_muscle: 'Quads', secondary_muscle: 'Glutes', movement_pattern: 'Squat', equipment_type: 'Dumbbell', force_vector: 'vertical', bilateral: false }
]

export const MUSCLE_GROUPS = [
  'Chest', 'Upper Chest', 'Mid Chest', 'Lower Chest',
  'Back', 'Lats', 'Upper Back', 'Lower Back',
  'Shoulders', 'Front Delts', 'Side Delts', 'Rear Delts',
  'Triceps', 'Biceps', 'Forearms',
  'Quads', 'Hamstrings', 'Glutes', 'Calves',
  'Adductors', 'Abductors', 'Hip Flexors',
  'Core', 'Abs', 'Obliques',
  'Traps', 'Neck', 'Tibialis',
]

export const MUSCLE_CHILDREN = {
  Chest: ['Upper Chest', 'Mid Chest', 'Lower Chest'],
  Back: ['Lats', 'Upper Back', 'Lower Back'],
  Shoulders: ['Front Delts', 'Side Delts', 'Rear Delts'],
  Core: ['Abs', 'Obliques'],
}

export const MOVEMENT_PATTERNS = ['Push', 'Pull', 'Squat', 'Hinge', 'Fly', 'Isolation']
export const EQUIPMENT_TYPES = ['Barbell', 'EZ-Bar', 'Dumbbell', 'Cable', 'Machine', 'Bodyweight', 'Smith Machine', 'Kettlebell', 'Trap Bar', 'Landmine', 'Plate']
export const FORCE_VECTORS = ['horizontal', 'vertical', 'diagonal']

export function getAllExercises(customExercises = []) {
  return [...SEED_EXERCISES, ...customExercises]
}

export function getExerciseById(id, customExercises = []) {
  return getAllExercises(customExercises).find(e => e.id === id) || null
}
